{% set name = "event-stream" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/event_stream-{{ version }}.tar.gz
  sha256: 9146264f5a0f276cbaafe98c8b2340339dd3ef1e62061e92f9c5a992ce8ebe41

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - pip
  run:
    - python

test:
  imports:
    - event_stream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphicsystems/event_stream
  summary: Read and write Event Stream (.es) files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
